Autocomplete
HubertLegec/CodersCamp2020_WarszawskiZbiorKom pull request #13
Opened 2021-01-11 19:12 UTC by brudek

Wrzuciłem bibliotekę autocomplete.js, w razie testów, dodajcie ją do package.json i 'npm i'

2021-01-13 18:07 UTC, HubertLegec requested changes

2021-01-13 18:07 UTC, HubertLegec commented on src/app/SearchManager.js
> +                let data = await JSON.parse(window.localStorage.stopsList);
nie powinniśmy sięgać bezpośrednio do local storage tutaj. Mamy już klasę `StorageManager` która tu powinna być dostarczona w konstruktorze i wykorzystania do pobrania wartości

2021-01-13 18:07 UTC, HubertLegec commented on src/app/SearchManager.js
> +                .map(s => s = {...s, ...{Nazwa : `${s.name} ${s.number}`}})
tu nie na potrzeby wewnątrz tworzyć obiektu żeby go rozwinąć operatorem `...`, wystarczy:
`.map(s => s = {...s, Nazwa : `${s.name} ${s.number}`})`
Swoją drogą atrybut `Nazwa` to słaby pomysł, konsekwentnie po angielsku i z małej litery trzeba jechać

2021-01-13 18:07 UTC, HubertLegec commented on test/InputSearch.spec.js
> +const autocompleteInput = document.getElementById('autoComplete');
metoda `createInput` powinna zwracać to co stworzyła, wtedy nie będzie potrzeby jeszcze raz wyciągania tego z dokumentu.
Cały ten kod przygotowujący do testu powinien się znaleźć w `beforeEach` wewnątrz describe

2021-01-13 18:07 UTC, HubertLegec commented on test/InputSearch.spec.js
> +        expect(autocompleteInput.value = "łąkowa").toBe("łąkowa");
nie widzę miejsca gdzie zaczynasz wpisywać coś w input żeby wyświetliły się jakieś podpowiedzi.
skąd się tu bierze ta `łąkowa` od razu?

2021-01-13 21:26 UTC, brudek commented on src/app/App.js
> +    document.querySelector("#autoComplete").addEventListener("results", (event) => {
To jest z tej biblioteki autocomplete.js. Widzę, że niepotrzebnie dodałem 'name' do konstruktora, bo to miała być wersja, gdybyśmy w innych miejscach chcieli wyszukiwać po innym kluczu

2021-01-13 21:29 UTC, brudek commented on src/app/SearchManager.js
> +                .map(s => s = {...s, ...{Nazwa : `${s.name} ${s.number}`}})
"Nazwa" dałem, bo to jest klucz który się wyświetla w rozwijalnej liście (taką ledwo widoczną czcionką). Zmienię, żeby tylko przy wyświetlaniu była polska nazwa

2021-01-16 14:51 UTC, HubertLegec approved these changes

2021-01-17 20:00 UTC, tmassalski approved these changes

2021-01-17 20:01 UTC, merged